data:
  image: alpine
  volumes:
    - ~/.m2:/root/.m2
  command: "/bin/sh"

install:
  image: maven
  volumes:
    - ./:/app
    - ~/.m2:/root/.m2
  working_dir: /app
  command: "mvn install"

test:
  image: maven
  volumes:
    - ./:/app
    - ~/.m2:/root/.m2
  working_dir: /app
  command: "mvn cobertura:cobertura test"

server:
  image: maven
  volumes:
    - ./:/app
    - ~/.m2:/root/.m2
  working_dir: /app
  ports:
   - "8000:8000"
  command: "mvn spring-boot:run"

package:
  image: maven
  volumes:
    - ./:/app
    - ~/.m2:/root/.m2
  working_dir: /app
  command: "mvn package"

clean:
  image: maven
  volumes:
    - ./:/app
    - ~/.m2:/root/.m2
  working_dir: /app
  command: "mvn clean" 